# Generated by Django 5.1.4 on 2026-07-25 12:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("school_years", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("registration", "Frais d'inscription"),
                            ("monthly", "Mensualité"),
                            ("exam", "Frais d'examen"),
                            ("transport", "Transport"),
                            ("other", "Autres frais"),
                        ],
                        max_length=20,
                        verbose_name="Type de frais",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Ex: Frais d'inscription 2025-2026",
                        max_length=150,
                        verbose_name="Libellé",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant (CDF)",
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=True, verbose_name="Obligatoire"),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance"
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laisser vide pour appliquer à tous les niveaux.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fee_configs",
                        to="academics.level",
                        verbose_name="Niveau",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laisser vide pour appliquer à toutes les options.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fee_configs",
                        to="academics.option",
                        verbose_name="Option",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_configs",
                        to="school_years.schoolyear",
                        verbose_name="Année scolaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration des frais",
                "verbose_name_plural": "Configurations des frais",
                "ordering": ["school_year", "fee_type", "label"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Montant payé (CDF)",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Espèces"),
                            ("mobile_money", "Mobile Money"),
                            ("bank_transfer", "Virement bancaire"),
                            ("check", "Chèque"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="Moyen de paiement",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Date de paiement")),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Générée automatiquement si laissée vide.",
                        max_length=50,
                        unique=True,
                        verbose_name="Référence",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_recorded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enregistré par",
                    ),
                ),
                (
                    "fee_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="finance.feeconfig",
                        verbose_name="Type de frais",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="school_years.schoolyear",
                        verbose_name="Année scolaire",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="students.student",
                        verbose_name="Élève",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "receipt_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro de reçu"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="receipts/",
                        verbose_name="Fichier PDF",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Généré le"),
                ),
                (
                    "generation_failed",
                    models.BooleanField(
                        default=False, verbose_name="Échec de génération"
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt",
                        to="finance.payment",
                        verbose_name="Paiement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reçu de paiement",
                "verbose_name_plural": "Reçus de paiements",
                "ordering": ["-generated_at"],
            },
        ),
    ]
