# Generated by Django 5.1.4 on 2026-07-25 12:06

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Ex: A, B, ou Classe 1",
                        max_length=50,
                        verbose_name="Nom de la classe",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=40,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Capacité (élèves)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classe",
                "verbose_name_plural": "Classes",
                "ordering": ["school_year", "option__level__order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du niveau"),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, verbose_name="Code"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="0 = premier niveau, croissant",
                        verbose_name="Ordre d'affichage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Niveau",
                "verbose_name_plural": "Niveaux",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom de l'option"),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Option / Filière",
                "verbose_name_plural": "Options / Filières",
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nom / Numéro de salle"
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("classroom", "Salle de classe"),
                            ("laboratory", "Laboratoire"),
                            ("computer_lab", "Salle informatique"),
                            ("library", "Bibliothèque"),
                            ("gymnasium", "Gymnase"),
                            ("other", "Autre"),
                        ],
                        default="classroom",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=40,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Capacité",
                    ),
                ),
                (
                    "equipment",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste JSON des équipements disponibles (ex: ['projecteur', 'tableau'])",
                        verbose_name="Équipements",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Décochez si la salle est temporairement hors service.",
                        verbose_name="Disponible",
                    ),
                ),
                (
                    "floor",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Étage / Bâtiment"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Salle",
                "verbose_name_plural": "Salles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Nom de la matière"),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Matière",
                "verbose_name_plural": "Matières",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubjectLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weekly_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=1,
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(0.5)],
                        verbose_name="Heures/semaine",
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=True, verbose_name="Obligatoire"),
                ),
            ],
            options={
                "verbose_name": "Matière par niveau",
            },
        ),
    ]
