# Generated by Django 5.1.4 on 2026-07-25 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("school_years", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="school_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to="school_years.schoolyear",
                verbose_name="Année scolaire",
            ),
        ),
        migrations.AddField(
            model_name="level",
            name="school_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="levels",
                to="school_years.schoolyear",
                verbose_name="Année scolaire",
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="academics.level",
                verbose_name="Niveau",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to="academics.option",
                verbose_name="Option",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="main_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_classrooms",
                to="academics.room",
                verbose_name="Salle principale",
            ),
        ),
        migrations.AddField(
            model_name="subjectlevel",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.level"
            ),
        ),
        migrations.AddField(
            model_name="subjectlevel",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.subject"
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="levels",
            field=models.ManyToManyField(
                related_name="subjects",
                through="academics.SubjectLevel",
                to="academics.level",
                verbose_name="Niveaux",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="level",
            unique_together={("school_year", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="option",
            unique_together={("level", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="classroom",
            unique_together={("school_year", "option", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="subjectlevel",
            unique_together={("subject", "level")},
        ),
    ]
