# Generated by Django 5.1.4 on 2026-07-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Un niveau inactif ne peut pas être utilisé pour créer des classes.",
                verbose_name="Actif",
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Une option inactive ne peut pas être utilisée pour créer des classes.",
                verbose_name="Active",
            ),
        ),
    ]
