# Generated by Django 5.1.4 on 2026-07-25 12:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("school_years", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("document", "Document"),
                            ("audio", "Audio"),
                            ("video", "Vidéo"),
                            ("link", "Lien externe"),
                            ("image", "Image"),
                        ],
                        default="pdf",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resources/%Y/%m/",
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Pour les liens YouTube, Drive, etc.",
                        verbose_name="URL externe",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Taille (octets)"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Décochez pour masquer temporairement aux élèves.",
                        verbose_name="Publié",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="school_years.schoolyear",
                        verbose_name="Année scolaire",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="academics.subject",
                        verbose_name="Matière",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Publié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ressource pédagogique",
                "verbose_name_plural": "Ressources pédagogiques",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResourceAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laisser vide si l'accès est par niveau.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_accesses",
                        to="academics.classroom",
                        verbose_name="Classe",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laisser vide si l'accès est par classe.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_accesses",
                        to="academics.level",
                        verbose_name="Niveau",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_rules",
                        to="resources.resource",
                        verbose_name="Ressource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règle d'accès",
                "verbose_name_plural": "Règles d'accès",
            },
        ),
    ]
