# Generated by Django 5.1.4 on 2026-07-25 12:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("school_years", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("body", models.TextField(verbose_name="Contenu")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("announcement", "Annonce"),
                            ("alert", "Alerte"),
                            ("convocation", "Convocation"),
                            ("payment_reminder", "Rappel de paiement"),
                        ],
                        default="announcement",
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "target_all",
                    models.BooleanField(
                        default=False,
                        help_text="Si coché, le message est visible par tous.",
                        verbose_name="Tous les parents/élèves",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publié le"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Envoyé par",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="school_years.schoolyear",
                        verbose_name="Année scolaire",
                    ),
                ),
                (
                    "target_classrooms",
                    models.ManyToManyField(
                        blank=True,
                        related_name="messages",
                        to="academics.classroom",
                        verbose_name="Classes ciblées",
                    ),
                ),
                (
                    "target_levels",
                    models.ManyToManyField(
                        blank=True,
                        related_name="messages",
                        to="academics.level",
                        verbose_name="Niveaux ciblés",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "read_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Lu le"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="communications.message",
                        verbose_name="Message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_reads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lecture de message",
                "verbose_name_plural": "Lectures de messages",
                "unique_together": {("message", "user")},
            },
        ),
    ]
