# Generated by Django 5.1.4 on 2026-07-25 12:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("school_years", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        max_length=1,
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Téléphone principal"),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone secondaire"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "profession",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Profession"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compte utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent / Tuteur",
                "verbose_name_plural": "Parents / Tuteurs",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "matricule",
                    models.CharField(
                        help_text="Généré automatiquement à l'inscription.",
                        max_length=30,
                        unique=True,
                        verbose_name="Matricule",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                ("date_of_birth", models.DateField(verbose_name="Date de naissance")),
                (
                    "place_of_birth",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Lieu de naissance"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        max_length=1,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        default="Congolaise", max_length=100, verbose_name="Nationalité"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="students/photos/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Groupe sanguin"
                    ),
                ),
                (
                    "medical_notes",
                    models.TextField(blank=True, verbose_name="Notes médicales"),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Contact d'urgence"
                    ),
                ),
                (
                    "emergency_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Tél. d'urgence"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compte utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élève",
                "verbose_name_plural": "Élèves",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="ParentStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("father", "Père"),
                            ("mother", "Mère"),
                            ("guardian", "Tuteur légal"),
                            ("other", "Autre"),
                        ],
                        default="guardian",
                        max_length=20,
                        verbose_name="Lien de parenté",
                    ),
                ),
                (
                    "is_emergency_contact",
                    models.BooleanField(
                        default=False, verbose_name="Contact d'urgence"
                    ),
                ),
                (
                    "is_authorized_pickup",
                    models.BooleanField(
                        default=True, verbose_name="Autorisé à récupérer l'enfant"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_links",
                        to="students.parent",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_links",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien Parent-Élève",
                "verbose_name_plural": "Liens Parent-Élève",
                "unique_together": {("parent", "student")},
            },
        ),
        migrations.AddField(
            model_name="parent",
            name="students",
            field=models.ManyToManyField(
                related_name="parents",
                through="students.ParentStudent",
                to="students.student",
                verbose_name="Enfants",
            ),
        ),
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("transferred", "Transféré"),
                            ("graduated", "Diplômé"),
                            ("dropped", "Abandonné"),
                            ("repeating", "Redoublant"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date d'inscription"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="academics.classroom",
                        verbose_name="Classe",
                    ),
                ),
                (
                    "enrolled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollments_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Inscrit par",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="school_years.schoolyear",
                        verbose_name="Année scolaire",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="students.student",
                        verbose_name="Élève",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription",
                "verbose_name_plural": "Inscriptions",
                "ordering": ["-school_year__start_date", "student__last_name"],
                "unique_together": {("student", "school_year")},
            },
        ),
    ]
