# Generated by Django 5.1.4 on 2026-07-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_student_matricule"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentenrollment",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("active", "Active"),
                    ("completed", "Terminée"),
                    ("cancelled", "Annulée"),
                    ("transferred", "Transféré"),
                    ("graduated", "Diplômé"),
                    ("dropped", "Abandonné"),
                    ("repeating", "Redoublant"),
                ],
                default="active",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
