# Generated by Django 5.1.4 on 2026-07-25 12:06

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nom de l'établissement"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Identifiant URL")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email de contact"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Congo (RDC)", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="schools/logos/",
                        verbose_name="Logo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("trial", "Essai"),
                            ("active", "Actif"),
                            ("suspended", "Suspendu"),
                            ("expired", "Expiré"),
                        ],
                        default="trial",
                        max_length=20,
                        verbose_name="Statut abonnement",
                    ),
                ),
                (
                    "subscription_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expiration abonnement"
                    ),
                ),
                (
                    "setup_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Mis à True après que l'Admin école a complété l'assistant de configuration",
                        verbose_name="Configuration initiale terminée",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "École",
                "verbose_name_plural": "Écoles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domaine",
                "verbose_name_plural": "Domaines",
            },
        ),
    ]
