# Generated by Django 5.1.4 on 2026-07-25 12:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("school_years", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("monday", "Lundi"),
                            ("tuesday", "Mardi"),
                            ("wednesday", "Mercredi"),
                            ("thursday", "Jeudi"),
                            ("friday", "Vendredi"),
                            ("saturday", "Samedi"),
                        ],
                        max_length=10,
                        verbose_name="Jour",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                ("end_time", models.TimeField(verbose_name="Heure de fin")),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Période 1, Récréation, Déjeuner",
                        max_length=50,
                        verbose_name="Libellé",
                    ),
                ),
                (
                    "is_break",
                    models.BooleanField(
                        default=False,
                        help_text="Cochez pour les récréations/pauses (non assignables).",
                        verbose_name="Pause",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="school_years.schoolyear",
                        verbose_name="Année scolaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Créneau horaire",
                "verbose_name_plural": "Créneaux horaires",
                "ordering": ["day", "start_time"],
                "unique_together": {("school_year", "day", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="academics.classroom",
                        verbose_name="Classe",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedules",
                        to="academics.room",
                        verbose_name="Salle",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="school_years.schoolyear",
                        verbose_name="Année scolaire",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="academics.subject",
                        verbose_name="Matière",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="teachers.teacher",
                        verbose_name="Enseignant",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="scheduling.timeslot",
                        verbose_name="Créneau",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cours planifié",
                "verbose_name_plural": "Cours planifiés",
                "ordering": [
                    "time_slot__day",
                    "time_slot__start_time",
                    "classroom__name",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("teacher", "time_slot"),
                        name="unique_teacher_per_timeslot",
                    ),
                    models.UniqueConstraint(
                        fields=("classroom", "time_slot"),
                        name="unique_classroom_per_timeslot",
                    ),
                ],
            },
        ),
    ]
