# Generated by Django 5.1.4 on 2026-07-25 12:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("school_years", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        unique=True,
                        verbose_name="Matricule employé",
                    ),
                ),
                (
                    "specialization",
                    models.TextField(blank=True, verbose_name="Spécialisation"),
                ),
                (
                    "hire_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'embauche"
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent"),
                            ("temporary", "Temporaire"),
                            ("volunteer", "Bénévole"),
                        ],
                        default="permanent",
                        max_length=30,
                        verbose_name="Type de contrat",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biographie")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compte utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enseignant",
                "verbose_name_plural": "Enseignants",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="TeacherSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=True,
                        help_text="Distingue la matière principale des matières secondaires.",
                        verbose_name="Matière principale",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laisser vide = toutes les niveaux pour cette matière.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.level",
                        verbose_name="Niveau",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_qualifications",
                        to="academics.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_qualifications",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qualification enseignant",
                "verbose_name_plural": "Qualifications enseignants",
                "unique_together": {("teacher", "subject", "level")},
            },
        ),
        migrations.AddField(
            model_name="teacher",
            name="subjects",
            field=models.ManyToManyField(
                related_name="teachers",
                through="teachers.TeacherSubject",
                to="academics.subject",
                verbose_name="Matières enseignées",
            ),
        ),
        migrations.CreateModel(
            name="TeacherAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("monday", "Lundi"),
                            ("tuesday", "Mardi"),
                            ("wednesday", "Mercredi"),
                            ("thursday", "Jeudi"),
                            ("friday", "Vendredi"),
                            ("saturday", "Samedi"),
                        ],
                        max_length=10,
                        verbose_name="Jour",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                ("end_time", models.TimeField(verbose_name="Heure de fin")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Disponible"),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_availabilities",
                        to="school_years.schoolyear",
                        verbose_name="Année scolaire",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="teachers.teacher",
                        verbose_name="Enseignant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disponibilité enseignant",
                "verbose_name_plural": "Disponibilités enseignants",
                "ordering": ["teacher", "day", "start_time"],
                "unique_together": {("teacher", "school_year", "day", "start_time")},
            },
        ),
    ]
