# Generated by Django 5.1.4 on 2026-07-25 19:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonnelNumberConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "next_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Prochain numéro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration des matricules du personnel",
                "verbose_name_plural": "Configuration des matricules du personnel",
            },
        ),
        migrations.AlterField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teacher_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Compte utilisateur",
            ),
        ),
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        help_text="Généré automatiquement par KLASS.",
                        max_length=30,
                        unique=True,
                        verbose_name="Matricule du personnel",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        max_length=1,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "specialization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Spécialité"
                    ),
                ),
                (
                    "staff_type",
                    models.CharField(
                        choices=[
                            ("teacher", "Enseignant"),
                            ("administrative", "Personnel administratif"),
                            ("management", "Personnel de direction"),
                            ("technical", "Personnel technique"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Type de personnel",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("inactive", "Inactif"),
                            ("on_leave", "En congé"),
                            ("suspended", "Suspendu"),
                            ("archived", "Archivé"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Niveau d'étude"
                    ),
                ),
                (
                    "diploma",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Diplôme"
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Années d'expérience"
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'embauche"
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent"),
                            ("temporary", "Temporaire"),
                            ("volunteer", "Bénévole"),
                        ],
                        default="permanent",
                        max_length=30,
                        verbose_name="Type de contrat",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personnel_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compte de connexion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre du personnel",
                "verbose_name_plural": "Membres du personnel",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.AddField(
            model_name="teacher",
            name="personnel",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_profile",
                to="teachers.personnel",
                verbose_name="Dossier personnel",
            ),
        ),
    ]
