# Generated by Django 5.1.4 on 2026-07-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_years", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolyear",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Une année archivée est définitivement fermée.",
                verbose_name="Archivée",
            ),
        ),
    ]
